### ISSUE TITLE
License

### ISSUE THREAD

**Issue by benjamingr** [zhenv5/breaking_cycles_in_noisy_hierarchies#1]
Hey, is this code licensed for reuse :)?

**Comment by brightbyte** [comment]
I would also be very interested to know this. I'm investigating the use of this code for cleaning up the MediaWiki code base. Without knowing the license of this code, we can't use it. That would be a shame, it works great for that application!

**Comment by zhenv5** [comment]
A BSD Licence is added.

**Comment by benjamingr** [comment]
Thanks @zhenv5 !
