### ISSUE TITLE
Running break_cycles.py on my own edges data from command line and returning "could not find socialagony file"

### ISSUE THREAD

**Issue by draftin1** [zhenv5/breaking_cycles_in_noisy_hierarchies#3]
I am getting the following error when I run the break_cycles.py from the command line.
The program directs to the social agony compute .py file, and changes the string to be of agony data rather than my data.

`iLost:breaking_cycles_in_noisy_hierarchies-master home$ python break_cycles.py -g /Users/software/breaking_cycles_in_noisy_hierarchies-master/data/adjective-edgelist.edges
dir name: /Users/software/breaking_cycles_in_noisy_hierarchies-master/data, file_name: adjective-edgelist.edges
start computing socialagony...
dir name: /Users/software/breaking_cycles_in_noisy_hierarchies-master/data, file_name: adjective-edgelist.edges
running command: agony/agony /Users/software/breaking_cycles_in_noisy_hierarchies-master/data/adjective-edgelist.edges /Users/software/breaking_cycles_in_noisy_hierarchies-master/data/adjective-edgelist_socialagony.txt
agony/agony /Users/software/breaking_cycles_in_noisy_hierarchies-master/data/adjective-edgelist.edges /Users/software/breaking_cycles_in_noisy_hierarchies-master/data/adjective-edgelist_socialagony.txt
/bin/sh: agony/agony: cannot execute binary file
time used in computing social agony: 0.0000 s
====compute agony done=====
Traceback (most recent call last):
  File "break_cycles.py", line 35, in <module>
    break_cycles(args.graph_file,args.gt_edges_file,args.method,nodetype = int)
  File "break_cycles.py", line 23, in break_cycles
    evaluation(graph_file,extra_edges_file,algorithm,nodetype = nodetype)
  File "break_cycles.py", line 14, in evaluation
    breaking_cycles_by_hierarchy_performance(graph_file,gt_edges_file,method,nodetype = nodetype)
  File "/Users/software/breaking_cycles_in_noisy_hierarchies-master/remove_cycle_edges_by_hierarchy.py", line 114, in breaking_cycles_by_hierarchy_performance
    players_score_dict  = computing_hierarchy(graph_file,"socialagony",nodetype = nodetype)
  File "/Users/software/breaking_cycles_in_noisy_hierarchies-master/remove_cycle_edges_by_hierarchy.py", line 59, in computing_hierarchy
    players = compute_social_agony(graph_file,agony_path = "agony/agony ")
  File "/Users/software/breaking_cycles_in_noisy_hierarchies-master/compute_social_agony.py", line 23, in compute_social_agony
    agony_score = read_dict_from_file(output)
  File "/Users/software/breaking_cycles_in_noisy_hierarchies-master/file_io.py", line 72, in read_dict_from_file
    input_file = open(file_name,"r")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/software/breaking_cycles_in_noisy_hierarchies-master/data/adjective-edgelist_socialagony.txt'`

**Comment by zhenv5** [comment]
1. you have to use code in the agony folder to computer the social agony. 2. You can specify to use TrueSkill to compute the graph hierarchy.
